sudo: true
dist: trusty

language: node_js

cache: npm

install:
  - npm i -g npm@latest
  - npm i --production

env:
  global:
    - SEQ_DB=sequelize_test
    - SEQ_USER=sequelize_test
    - SEQ_PW=sequelize_test
    - SEQ_HOST=127.0.0.1

before_script:
  - . ./setup/travis-ci-helper.sh

script:
  - npm run ci

jobs:
  include:
    - name: sqlite
      node_js: '10'
      env: 
        - DIALECT=sqlite
        - DIALECT=sqlite USE_TS=true
    - name: mysql
      node_js: '10'
      sudo: required
      env:
        - MYSQL_VER=mysql-57 SEQ_MYSQL_PORT=8980 DIALECT=mysql
        - MYSQL_VER=mysql-57 SEQ_MYSQL_PORT=8980 DIALECT=mysql USE_TS=true
    - name: mariadb
      node_js: '10'
      sudo: required
      env:
        - MARIADB_VER=mariadb-103 SEQ_MARIADB_PORT=8960 DIALECT=mariadb
        - MARIADB_VER=mariadb-103 SEQ_MARIADB_PORT=8960 DIALECT=mariadb USE_TS=true
    - name: postgres
      node_js: '10'
      sudo: required
      env:
        - POSTGRES_VER=postgres-10 SEQ_PG_PORT=8991 DIALECT=postgres
        - POSTGRES_VER=postgres-10 SEQ_PG_PORT=8991 DIALECT=postgres USE_TS=true
